### ISSUE TITLE
npm istall fails after update to the latest version

### ISSUE THREAD

**Issue by antonevane** [tomwanzek/d3-ng2-service#99]
npm ERR! path C:\app\node_modules\d3-ng2-service
npm ERR! code EISGIT
npm ERR! git C:\app\node_modules\d3-ng2-service: Appears to be a git repo or submodule.
npm ERR! git     C:\app\node_modules\d3-ng2-service
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.

npm ERR! A complete log of this run can be found in:
npm ERR!    C:\user1\AppData\Roaming\npm-cache\_logs\2017-11-27T18_27_43_756Z-debug.log

**Comment by tomwanzek** [comment]
@antonevane Thanks for alerting me to this issue. I am able to install the latest version into a blank project without issues. I.e.:
* new directory
* `npm init`
* `npm install d3-ng2-service`.

However, if I attempt to install into an existing project, e. g. a `nrwl/nx` based monorepo, I run into the same issue. I do, however, get an `npm` `EPERM` error related to the non-existing `fsevent` upon my first install attempt. On the second attempt, I get the error you posted.

I am tempted to believe, it's an npm issue (at least the error message seems misguiding). Could you let me know your:
* node/npm versions
* platform/OS
* Angular version
* any version of Angular-cli or nrwl/nx or similar tooling that might form the basis of your repo?

Thanks in advance for the additional info.

**Comment by antonevane** [comment]
Node version: _v6.11.2_, _6.10.3_
Npm versions: _5.5.1_, _3.10.10_
OS:                  Window, rhel71 linux cbuild_rhel7
Angular:          4.4.6
angular/cli:      1.4.9

**Comment by skyboys22** [comment]
i think the problem is relative to **d3-geojson**

https://github.com/DefinitelyTyped/DefinitelyTyped/issues/21794

**Comment by tomwanzek** [comment]
Thanks for the added info. For starters, I will publish a no-op patch release (just rebuild the project locally and bumping the patch release number).

Since I have not made any changes to the build/publish pipeline as such from version 1.22.1 to 1.23.0, which would explain the behavior, I'll have to see.

@antonevane @skyboys22 Can you confirm that installing version 1.22.1 works for you? That's when I changed some of the dev-dependencies.

**Comment by skyboys22** [comment]
maybe it's relative to this issue in d3-geojson https://github.com/DefinitelyTyped/DefinitelyTyped/issues/21794 ?

i will try 1.22.1 tonight
thank you

**Comment by tomwanzek** [comment]
@skyboys22 I was considering that as well. Although it seems strange. There is an active PR DefinitelyTyped/DefinitelyTyped#21801 which, once merged, will remove the compile error.

**Comment by tomwanzek** [comment]
I pushed a patch release (1.23.1), which will automatically pull the latest version of the **d3-geo** definitions (1.9.4). This is an interim patch addressing the  DefinitelyTyped/DefinitelyTyped#21794 geojson issue.

I just installed this latest version into a `nrwl\nx` based repo and the install worked.

So, please try this latest patch release and advise, if you are able to proceed without the utterly quirky npm error.

Thanks in advance for checking and confirming back.

**Comment by PandiyanCool** [comment]
Facing the same issue, trying 1.23.1 package now.

**Comment by PandiyanCool** [comment]
I'm able to install the package in empty folder. If I rerun the npm install command, the problem occurs.

Even after installing the latest package, I'm facing the same issue.

Check the attached image, the installed node_modules folder contains .git folder. May be this is reason of conflict between git and npm.

Check whether the npm publish properly ignored the git files and all.

![capture](https://user-images.githubusercontent.com/6157834/33365116-1f350fe4-d50d-11e7-89b7-27a5c466e09a.PNG)

**Comment by larssn** [comment]
Same problem as well:

Node version: v8.9.0
Npm versions: 5.5.1
OS: OSX High Sierra
Angular: 5.0.3
angular/cli: 1.5.4

**Comment by fuseme** [comment]
Also still seeing the issue

Node: 8.5.0
NPM: 5.3.0
OS: OSX Sierra
Angular: 4.4.6
Angular/CLI: 1.4.2

**Comment by tomwanzek** [comment]
Thanks for the patience. @PandiyanCool thanks for your comment. I had checked through VS Code, which of course did not list the `.git` in the installed version 😕 

The short story is that npm 5.5.1 is not currently ignoring the `.git` by default, as used to be the case (see npm/npm#19073) I explicitly npmignored it for now.

So version 1.23.2 works as intended again.

Closed by #101.
